/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.User_File;
import Controller.User_Class;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wajeeha Usman
 */
public class Del_User extends javax.swing.JFrame {

    /**
     * Creates new form Del_User
     */
    ArrayList <String>l=new ArrayList<>();
  
 
User_File F=new  User_File();
    public Del_User() {
        initComponents();
        model = (DefaultTableModel)TABLE.getModel();
        
        ViewDataInTable();
        
    }
    private DefaultTableModel model;
    
    private void ViewDataInTable(){
        
        ArrayList <User_Class> a =new ArrayList<>() ;
        a=F.readfromFile();
        
        for(User_Class u : a){
            Object[] o=new Object[4];
            
            o[0] = u.getName();
            o[1] = u.getEmail();
            o[2] = u.getCnic();
            o[3] = u.getPhone();
             
            model.addRow(o);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Backk = new javax.swing.JButton();
        del = new javax.swing.JButton();
        Exitt = new javax.swing.JButton();
        head = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(null);

        Backk.setText("Back");
        Backk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackkActionPerformed(evt);
            }
        });
        jPanel1.add(Backk);
        Backk.setBounds(30, 400, 90, 50);

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del);
        del.setBounds(240, 400, 90, 50);

        Exitt.setText("Exiit");
        Exitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExittActionPerformed(evt);
            }
        });
        jPanel1.add(Exitt);
        Exitt.setBounds(460, 400, 90, 50);

        head.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("DELETE USER INFORMATION");
        jPanel1.add(head);
        head.setBounds(120, 50, 310, 70);

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "CNIC", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TABLE);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 130, 452, 170);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackkActionPerformed
        // TODO update your handling code here:
        User_Info_AdminPanel u=new User_Info_AdminPanel();
        u.setVisible(true);
        u.setDefaultCloseOperation(0);
    }//GEN-LAST:event_BackkActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO update your handling code here:

        int r= TABLE.getSelectedRow();
          if(r!= -1){
          User_File fs=new User_File();
        ArrayList<User_Class> list=new ArrayList<>();
        list=fs.readfromFile();
        for(int i=0; i<list.size(); i++){
            if(r==i){
                list.remove(i);
                model.removeRow(r);
                JOptionPane.showMessageDialog(this, "Deleted succesfully");
            }
        } 
          
          fs.againWriteToFile();
          }
          else
              JOptionPane.showMessageDialog(this, "Please select any row and then press 'delete' button");
       

    }//GEN-LAST:event_delActionPerformed

    private void ExittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExittActionPerformed
        // TODO update your handling code here:
         Exit ex=new Exit();
       ex.setVisible(true);
       ex.setDefaultCloseOperation(0);
    }//GEN-LAST:event_ExittActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Del_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Del_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Del_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Del_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Del_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backk;
    private javax.swing.JButton Exitt;
    private javax.swing.JTable TABLE;
    private javax.swing.JButton del;
    private javax.swing.JLabel head;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
