/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.House_Class;
import Controller.House_File;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Wajeeha Usman
 */
public class UPDATE_HOUSES extends javax.swing.JFrame {

    /**
     * Creates new form UPDATE_HOUSES
     */
    public UPDATE_HOUSES() {
        initComponents();
    }
ArrayList <House_Class>arrayList=new ArrayList<>();
            House_File House_FileObj=new  House_File();
            House_Class  H_classobj=new House_Class();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        house_Owner_button = new javax.swing.JButton();
        house_Adress_button = new javax.swing.JButton();
        house_Storey_button = new javax.swing.JButton();
        house_Room_button = new javax.swing.JButton();
        house_To_Update = new javax.swing.JButton();
        House_Room_text = new javax.swing.JTextField();
        House_Storey_text = new javax.swing.JTextField();
        House_Adress_text = new javax.swing.JTextField();
        House_Oener_text = new javax.swing.JTextField();
        House_To_Up_text = new javax.swing.JTextField();
        UpdateHouse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLICK ON THE HOUSE YOU WANT TO UPDATE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 0, 480, 70);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(430, 360, 70, 40);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 350, 80, 50);

        house_Owner_button.setText("House Owner");
        house_Owner_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                house_Owner_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(house_Owner_button);
        house_Owner_button.setBounds(40, 150, 120, 40);

        house_Adress_button.setText("House Adress");
        jPanel1.add(house_Adress_button);
        house_Adress_button.setBounds(40, 200, 120, 40);

        house_Storey_button.setText("House Storey");
        jPanel1.add(house_Storey_button);
        house_Storey_button.setBounds(40, 250, 120, 40);

        house_Room_button.setText("House Room");
        jPanel1.add(house_Room_button);
        house_Room_button.setBounds(40, 300, 120, 40);

        house_To_Update.setText("House To Update");
        jPanel1.add(house_To_Update);
        house_To_Update.setBounds(40, 100, 120, 40);
        jPanel1.add(House_Room_text);
        House_Room_text.setBounds(200, 300, 210, 40);
        jPanel1.add(House_Storey_text);
        House_Storey_text.setBounds(200, 250, 210, 40);
        jPanel1.add(House_Adress_text);
        House_Adress_text.setBounds(200, 200, 210, 40);
        jPanel1.add(House_Oener_text);
        House_Oener_text.setBounds(200, 150, 210, 40);

        House_To_Up_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                House_To_Up_textActionPerformed(evt);
            }
        });
        jPanel1.add(House_To_Up_text);
        House_To_Up_text.setBounds(200, 100, 210, 40);

        UpdateHouse.setText("Update");
        UpdateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateHouseActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateHouse);
        UpdateHouse.setBounds(190, 360, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Exit ex=new Exit();
       ex.setVisible(true);
       ex.setDefaultCloseOperation(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       HOUSECRUD_ADMIN ah=new HOUSECRUD_ADMIN();
       ah.setVisible(true);
       ah.setDefaultCloseOperation(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void UpdateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateHouseActionPerformed
        // TODO add your handling code here:
         arrayList=House_FileObj.readfromFile();
     House_Class [] array_H_class=new House_Class [arrayList.size ()];
           
         for(int i=0;i<arrayList.size();i++)
         {
           
             array_H_class[i]=arrayList.get(i);
             
            String nameToUpdate= House_To_Up_text.getText();
            String Owner=House_Oener_text.getText();
            String Address=House_Adress_text.getText();
            String Storeys=House_Storey_text.getText();
            String Rooms=House_Room_text.getText();
           
            
            if(House_To_Up_text.getText().equalsIgnoreCase(array_H_class[i].getHouse_Owner())){
               
             array_H_class[i].setHouse_Owner(Owner);
             array_H_class[i].setHouse_Adress(Address);
             array_H_class[i].setHouse_Storeys(Storeys);
             array_H_class[i].setHouse_rooms(Rooms);
           H_classobj=new House_Class(Owner,Address,Storeys,Rooms);
           
            
           arrayList.set(i, H_classobj);
           House_FileObj.againWriteToFile();
            
            JOptionPane.showMessageDialog(this, "House Data Updated Successfully");
            JOptionPane.showInputDialog("DO YOY WANT TO UPDATE MORE DATA?");
            }else
            {
            JOptionPane.showMessageDialog(this, "The data of the house '"+House_To_Up_text.getText()+"' is not found ");
            break;
            }
       
         }
    }//GEN-LAST:event_UpdateHouseActionPerformed

    private void house_Owner_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_house_Owner_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_house_Owner_buttonActionPerformed

    private void House_To_Up_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House_To_Up_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House_To_Up_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE_HOUSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE_HOUSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE_HOUSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE_HOUSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE_HOUSES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField House_Adress_text;
    private javax.swing.JTextField House_Oener_text;
    private javax.swing.JTextField House_Room_text;
    private javax.swing.JTextField House_Storey_text;
    private javax.swing.JTextField House_To_Up_text;
    private javax.swing.JButton UpdateHouse;
    private javax.swing.JButton house_Adress_button;
    private javax.swing.JButton house_Owner_button;
    private javax.swing.JButton house_Room_button;
    private javax.swing.JButton house_Storey_button;
    private javax.swing.JButton house_To_Update;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
